---
license: CC-BY
---
# Privacy


::: {.callout}

This post was originally published at [edtechuvic.ca/edci339](https://edtechuvic.ca/edci339/?page_id=76). It is reproduced here under the original Creative Commons Attribution License.

:::

It is second nature to most to take selfies, share them on instagram, Snapchat, etc., but once you move into the role of a public school teacher, you must adhere to the laws set out by the B.C. Office of Information and Privacy Commissioner. Their office has put together guidelines for you to follow to better understand what the rules are and how to get consent, which is detailed on page 4:

[BC Cloud Computing Guidelines (PDF)](https://www.oipc.bc.ca/guidance-documents/2402)

and you can review the [Freedom of Information and Protection of Privacy Act here.](http://www.bclaws.ca/Recon/document/ID/freeside/96165_00)

Each school district will have their own process (which may range from not allowing to pressure to integrate networked learning tools from outside of Canada), so it is important to understand your school context. That said, you may find some school administrators or staff breaking these rules or not aware of them. As a preservice teacher, it is important for you to enter the field and uphold the law, regardless of the culture you enter. This does not mean that you do not engage online or outside of Canada. It means that if/when you do so, that you understand the steps, which are not much more complex than the consent you would get normally for going “on the Internet,” as is described in most schools, but you must name the date consent is effective and, if applicable, the date it expires. It is important that you work with your school district on the consent process. You can see an example of how school district are addressing access to cloud tools outside of Canada here and here (Victoria). You must also name each tool individually. It cannot be “blogging.” You must name WordPress.com or Blogger, etc. If you use Flipgrid, you must name Flipgrid. Consent must also be informed, so effort must be taken to ensure that those signing consent understand the implications. That their data may leave Canada, how it may be harvested, and to know about the U.S. Patriot Act. One archived resource by the Canadian Treasury Board provides significant detailed information about the Patriot Act here. It is important to also [review section 4(b) of the B.C. Digital Literacy Framework.](https://www2.gov.bc.ca/assets/gov/education/kindergarten-to-grade-12/teach/teaching-tools/digital-literacy-framework.pdf)

Additional resources can be found here:

[Privacy Education for Kids](https://www.priv.gc.ca/en/about-the-opc/what-we-do/awareness-campaigns-and-events/privacy-education-for-kids/) by the Office of the Privacy Commissioner of Canada

[Information Security Awareness](https://www2.gov.bc.ca/gov/content/governments/services-for-government/information-management-technology/information-security/information-security-awareness) by the BC Government

[MediaSmarts: Canada’s Centre for Digital and Media Literacy](http://mediasmarts.ca/)

## FIPPA, Privacy, and Consent Competencies

Teachers should ensure that they are:

- Aware of the OIPC, FIPPA, and the Cloud Computing Guidelines and follows them. 
- Understands what constitutes personal information. 
- Understands that privacy online is a personal choice and must be respected. 
- Understands that, as a preservice teacher or inservice teacher in the schools, that you assume a “public body” hat and have a duty of care for your learners, their parents and families, and your colleagues with regard to their privacy and protection of personal information. 
- Aware that the Canadian federal government states that the chances are remote that the US Patriot Act will access personal information of Canadians, but recognizes that it is our responsibility to protect privacy preferences and to ensure that consent obtained is informed consent. Some families may be involved with restraining orders and need to be private for their safety, but the reasons for privacy may be preference. Either way, it is not our business as to the reasons for privacy preferences, but it is our responsibility to uphold preferences.  
- Understands how media moves through networks into US cloud-based services (e.g., back-ups on iTunes, syncing with Dropbox, messages with personal information is sent on Gmail, blog RSS subscriptions, etc.). 
- Understands that these acts do not prohibit participation in networked tools outside of Canada and many school districts are in need of teachers who model networked literacy and positive citizenship online for their learners
- Familiar with section 4(b) of the BC Digital Literacy Framework and is prepared to integrate it in teaching and learning. 
- Understands what appropriate consent looks like for public bodies and is aware of what alternative steps are to support learners when consent is not obtained.
 